---
- name: Clean install Docker and run SonarQube container
  hosts: sonarqube
  become: true

  tasks:

    - name: Remove all lines mentioning download.docker.com in /etc/apt/sources.list
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^.*download\.docker\.com.*$'
        state: absent

    - name: Remove all rogue docker source files
      shell: |
        find /etc/apt/sources.list.d/ -type f -name "*docker*.list" -exec rm -f {} +
      args:
        executable: /bin/bash

    - name: Remove old Docker GPG key if it exists
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Update apt cache after cleanup
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Create directory for Docker keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository cleanly with signed-by
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker Engine and tools
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Run SonarQube container
      community.docker.docker_container:
        name: sonar
        image: sonarqube:lts-community
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9000:9000"